name: Auto Release

on:
  workflow_dispatch:
    inputs:
      bump_level:
        description: 'Version bump level (major, minor, patch, release, rc, beta, alpha)'
        required: true
        default: 'minor'
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          rust-version: stable

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Cargo Release
        run: cargo install cargo-release

      - name: Run Cargo Release
        run: cargo release ${{ github.event.inputs.bump_level }} --execute
