# .github/workflows/debug-precommit-dispatch.yml
name: Debug Mirror Trigger

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to send to mirror (optional)"
        required: false
        default: ""

jobs:
  trigger_pre_commit_update:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger mirror via workflow_dispatch
      env:
        GH_TOKEN: ${{ secrets.PRE_COMMIT_PAT }}
      run: |
        gh workflow run main.yaml \
          -R simone-viozzi/rusty-todo-md-pre-commit \
          --ref main \
          -f version="${{ inputs.version }}"

