name: Version Bump & Tag

permissions:
  contents: write 

on:
  workflow_dispatch:
    inputs:
      bump_level:
        description: 'Version bump level (major, minor, patch, release, rc, beta, alpha)'
        required: true
        default: 'minor'

jobs:
  version_bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Configure Git Identity
        run: |
          git config --global user.email "release-bot@example.com"
          git config --global user.name "Release Bot"

      - name: Set Up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          rust-version: stable

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Cargo Release
        run: cargo install cargo-release

      - name: Run Cargo Release (Bump Version)
        run: cargo release ${{ github.event.inputs.bump_level }} --execute --no-confirm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}
      
      - name: Get new version tag
        id: get_tag
        run: |
          NEW_TAG=$(git describe --tags --abbrev=0)
          echo "tag=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Install maturin
        run: pip install maturin

      - name: Build Wheel using maturin
        run: maturin build --release --bindings bin

      - name: List built wheels
        run: ls -l target/wheels/

      - name: Rename wheel file
        run: |
          mv target/wheels/*.whl target/wheels/rusty_todo_md-${{ steps.get_tag.outputs.tag }}.whl

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          name: Release ${{ steps.get_tag.outputs.tag }}
          body: Automated release generated by GitHub Actions.
          draft: true
          prerelease: false
          files: |
            target/wheels/rusty_todo_md-${{ steps.get_tag.outputs.tag }}.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}